Repository wJoenn/YogaUnalome, pull requests merged in 2023-06, with the labels that each got.

#61 added footer with just links & social icons
  app/frontend/images/logos/logo_text_black_clipped.png
  app/frontend/images/wave-green.png
  app/frontend/stylesheets/application.scss
  app/frontend/stylesheets/pages/_index.scss
  app/frontend/stylesheets/pages/partials/_footer.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_footer.html.erb
Labels: waiting for review, requires changes

#75 Stripe gem installed
  Gemfile
  Gemfile.lock
  app/controllers/bookings_controller.rb
  app/controllers/events_controller.rb
  app/frontend/javascript/controllers/booking_confirmation_controller.js
  app/frontend/javascript/controllers/index.js
  app/frontend/stylesheets/components/_booking.scss
  app/frontend/stylesheets/components/_buttons.scss
  app/frontend/stylesheets/components/_form.scss
  app/frontend/stylesheets/components/_index.scss
  app/frontend/stylesheets/components/_modal.scss
  app/frontend/stylesheets/config/_variables.scss
  app/frontend/stylesheets/pages/_home.scss
  app/models/booking.rb
  app/views/pages/home.html.erb
  app/views/pages/partials/_events_cards.html.erb
  app/views/shared/_booking_confirmation.html.erb
  config/initializers/stripe.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230529191522_add_payments_details_to_bookings.rb
  db/schema.rb
  spec/controllers/bookings_controller_spec.rb
Labels: waiting for review

#77 Transaction Model
  app/models/transaction.rb
  app/models/user.rb
  db/migrate/20230531120502_create_transactions.rb
  db/schema.rb
  spec/models/transaction_spec.rb
Labels: waiting for review

#79 Confirmable & Recoverable implemented with mailer
  app/frontend/stylesheets/components/_form.scss
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/devise.rb
  db/migrate/20230601140000_add_confirmable_to_devise.rb
  db/schema.rb
  spec/controllers/events_controller_spec.rb
  spec/rails_helper.rb
Labels: waiting for review

#84 Stripe webhooks after payment confirmation
  Gemfile
  Gemfile.lock
  app/controllers/bookings_controller.rb
  app/models/user.rb
  app/services/stripe_checkout_session_service.rb
  config/environments/development.rb
  config/initializers/stripe.rb
  config/routes.rb
  db/migrate/20230606193211_add_net_amount_to_transactions.rb
  db/schema.rb
Labels: waiting for review

#89 Stripe patch
  app/controllers/bookings_controller.rb
  app/frontend/javascript/controllers/booking_confirmation_controller.js
  app/models/booking.rb
  app/views/pages/partials/_events_cards.html.erb
  config/credentials.yml.enc
  config/initializers/stripe.rb
  db/migrate/20230608082523_remove_canceled_from_bookings.rb
  db/schema.rb
  spec/models/booking_spec.rb
Labels: bug, waiting for review

#91 Updated stripe checkout page's appearance
  app/controllers/bookings_controller.rb
  app/frontend/images/favicon.png
  app/views/layouts/application.html.erb
  db/seeds.rb
Labels: waiting for review

#92 Mailer layout
  Gemfile
  app/helpers/mailer_helper.rb
  app/mailers/application_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/confirmation_instructions.text.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.text.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  app/views/shared/_mailer_style.html.erb
  config/initializers/devise.rb
  spec/mailers/previews/devise_mailer_preview.rb
Labels: waiting for review

#96 en locales done with I18n
  Gemfile
  Gemfile.lock
  app/controllers/users/sessions_controller.rb
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/stylesheets/components/_buttons.scss
  app/frontend/stylesheets/config/_variables.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/confirmation_instructions.text.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/reset_password_instructions.text.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/confirmation.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pages/home.html.erb
  app/views/pages/partials/_about.html.erb
  app/views/pages/partials/_banner.html.erb
  app/views/pages/partials/_calendar.html.erb
  app/views/pages/partials/_events_cards.html.erb
  app/views/pages/partials/_footer.html.erb
  app/views/pages/partials/_planning.html.erb
  app/views/shared/_booking_confirmation.html.erb
  app/views/shared/_navbar.html.erb
  config/application.rb
  config/locales/en.yml
Labels: waiting for review

#88 Installed Good_Job for async jobs
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/application.rb
  config/initializers/good_job.rb
  config/routes.rb
  db/migrate/20230607164816_create_good_jobs.rb
  db/schema.rb
Labels: waiting for review

#98 Stripe refund
  app/controllers/bookings_controller.rb
  app/controllers/user_dashboard_controller.rb
  app/jobs/refund_booking_job.rb
  app/models/booking.rb
  app/services/stripe_charge_refund_service.rb
  app/views/user_dashboard/show.html.erb
  config/initializers/stripe.rb
  config/locales/en.yml
  spec/jobs/refund_booking_job_spec.rb
Labels: waiting for review

#100 Fr locales and switch button
  app/controllers/application_controller.rb
  app/frontend/javascript/controllers/user_form_modal_controller.js
  app/frontend/stylesheets/components/_navbar.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/confirmation.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/shared/_navbar.html.erb
  config/application.rb
  config/locales/devise.en.yml
  config/locales/devise.fr.yml
  config/locales/fr.yml
  config/routes.rb
  spec/controllers/events_controller_spec.rb
Labels: waiting for review
