Repository wJoenn/YogaUnalome, pull requests merged in 2023-05, with the labels that each got.

#33 RSpec gh action
  .github/workflows/test.yml
Labels: waiting for review

#36 Membership section
  app/frontend/stylesheets/application.scss
  app/frontend/stylesheets/components/_buttons.scss
  app/frontend/stylesheets/components/_index.scss
  app/frontend/stylesheets/config/_setup.scss
  app/frontend/stylesheets/config/_variables.scss
  app/frontend/stylesheets/pages/_home.scss
  app/frontend/stylesheets/pages/_index.scss
  app/frontend/stylesheets/pages/partials/membership.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_membership.html.erb
  package.json
  yarn.lock
Labels: waiting for review

#32 Session model
  app/models/session.rb
  db/migrate/20230502130714_create_sessions.rb
  db/schema.rb
  spec/models/session_spec.rb
Labels: waiting for review

#30 Devise model
  .github/workflows/linter.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20230502121355_devise_create_users.rb
  db/migrate/20230502121634_add_columns_to_u_sers.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: waiting for review

#39 Membership section v2
  app/frontend/images/illustrations/33.png
  app/frontend/images/illustrations/37.png
  app/frontend/stylesheets/components/_buttons.scss
  app/frontend/stylesheets/config/_setup.scss
  app/frontend/stylesheets/config/_variables.scss
  app/frontend/stylesheets/pages/partials/membership.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_membership.html.erb
Labels: waiting for review

#41 Calendar
  .rubocop.yml
  app/frontend/entrypoints/application.js
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/javascript/controllers/index.js
  app/frontend/stylesheets/config/_setup.scss
  app/frontend/stylesheets/pages/_home.scss
  app/frontend/stylesheets/pages/_index.scss
  app/frontend/stylesheets/pages/partials/_calendar.scss
  app/frontend/stylesheets/pages/partials/_membership.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_calendar.html.erb
  lib/generators/stimulus_custom/USAGE
  lib/generators/stimulus_custom/stimulus_custom_generator.rb
  lib/generators/stimulus_custom/templates/controller.js.tt
  lib/tasks/stimulus_tasks.rake
Labels: waiting for review

#38 Booking model
  Gemfile.lock
  app/models/booking.rb
  app/models/session.rb
  app/models/user.rb
  db/migrate/20230504172751_create_bookings.rb
  db/schema.rb
  spec/models/booking_spec.rb
Labels: requires changes

#45 Rspec patch for Booking
  .gitignore
  spec/models/booking_spec.rb
  spec/models/session_spec.rb
  spec/models/user_spec.rb
Labels: waiting for review

#46 Sessions inside javascript calendar
  app/controllers/pages_controller.rb
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/stylesheets/pages/partials/_calendar.scss
  app/models/event.rb
  app/views/pages/partials/_calendar.html.erb
  spec/models/event_spec.rb
Labels: waiting for review

#58 Renamed sessions reference to events
  app/controllers/pages_controller.rb
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/stylesheets/pages/partials/_calendar.scss
  app/views/pages/partials/_calendar.html.erb
Labels: waiting for review

#60 Money-rails + calendar bug fix
  Gemfile
  Gemfile.lock
  app/controllers/events_controller.rb
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/stylesheets/pages/partials/_calendar.scss
  app/models/event.rb
  app/views/events/new.html.erb
  config/initializers/money.rb
  db/migrate/20230511150708_add_price_to_events.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/events_controller_spec.rb
  spec/models/booking_spec.rb
  spec/models/event_spec.rb
  spec/models/user_spec.rb
Labels: waiting for review

#37 Banner
  app/frontend/stylesheets/components/_banner.scss
  app/frontend/stylesheets/components/_buttons.scss
  app/frontend/stylesheets/components/_index.scss
  app/frontend/stylesheets/components/_navbar.scss
  app/frontend/stylesheets/config/_setup.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_banner.html.erb
  app/views/shared/_navbar.html.erb
Labels: requires changes

#55 bookings controller
  app/controllers/bookings_controller.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/bookings_controller_spec.rb
Labels: requires changes

#59 Event Card Component - Start
  Gemfile.lock
  app/controllers/events_controller.rb
  app/controllers/pages_controller.rb
  app/frontend/javascript/controllers/calendar_controller.js
  app/frontend/stylesheets/config/_variables.scss
  app/frontend/stylesheets/pages/_home.scss
  app/frontend/stylesheets/pages/_index.scss
  app/frontend/stylesheets/pages/partials/_calendar.scss
  app/frontend/stylesheets/pages/partials/_events_cards.scss
  app/models/event.rb
  app/views/events/edit.html.erb
  app/views/pages/home.html.erb
  app/views/pages/partials/_calendar.html.erb
  app/views/pages/partials/_events_cards.html.erb
  config/routes.rb
  db/migrate/20230515043611_add_title_to_events.rb
  db/seeds.rb
  spec/controllers/bookings_controller_spec.rb
  spec/controllers/events_controller_spec.rb
  spec/models/booking_spec.rb
  spec/models/event_spec.rb
  spec/models/user_spec.rb
Labels: requires changes

#67 About Section
  app/frontend/images/illustrations/about_fern.png
  app/frontend/stylesheets/pages/_home.scss
  app/frontend/stylesheets/pages/_index.scss
  app/frontend/stylesheets/pages/partials/_about.scss
  app/views/pages/home.html.erb
  app/views/pages/partials/_about.html.erb
Labels: waiting for review

#69 Flash component
  app/frontend/javascript/controllers/flashes_controller.js
  app/frontend/javascript/controllers/index.js
  app/frontend/stylesheets/components/_flashes.scss
  app/frontend/stylesheets/components/_form.scss
  app/frontend/stylesheets/components/_index.scss
  app/frontend/stylesheets/config/_variables.scss
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_flashes.html.erb
Labels: waiting for review

#74 Fixed stimulus conflict with Vite
  Gemfile
  Gemfile.lock
  config/initializers/stimulus.rb
  lib/generators/.keep
  lib/generators/stimulus_custom/USAGE
  lib/generators/stimulus_custom/stimulus_custom_generator.rb
  lib/generators/stimulus_custom/templates/controller.js.tt
  lib/tasks/stimulus_tasks.rake
Labels: bug, waiting for review
